In [1]:
import numpy as np


In [2]:
features = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

# labels = np.array([0,0,0,1]) # AND GATE
labels = np.array([0,1,1,1]) # OR GATE

In [3]:
w = [0.2,0.3]

In [4]:
threshold = 0.5

In [5]:
learning_rate = 0.1
epoch = 10

In [6]:
for j in range(0,epoch):
    global_delta = 0
    for i in range(0,features.shape[0]):
        instance = features[i]
        actual = labels[i]
        
        x0 = instance[0]
        x1 = instance[1]

        sum_unit = x0*w[0] + x1*w[1]

        if sum_unit > threshold:
            fire = 1
        else:
            fire = 0

        delta = actual - fire
        global_delta = global_delta + abs(delta)
        
        print("prediction:", fire, "actual:", actual, "error:",delta)

        w[0] = w[0]+delta*learning_rate
        w[1] = w[1]+delta*learning_rate
        
    print("-------------------")
    
    if global_delta == 0:
        break


prediction: 0 actual: 0 error: 0
prediction: 0 actual: 1 error: 1
prediction: 0 actual: 1 error: 1
prediction: 1 actual: 1 error: 0
-------------------
prediction: 0 actual: 0 error: 0
prediction: 0 actual: 1 error: 1
prediction: 0 actual: 1 error: 1
prediction: 1 actual: 1 error: 0
-------------------
prediction: 0 actual: 0 error: 0
prediction: 1 actual: 1 error: 0
prediction: 1 actual: 1 error: 0
prediction: 1 actual: 1 error: 0
-------------------


In [7]:
print("updated weights:",w)

updated weights: [0.6, 0.7]


In [8]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01): 
    # Fill in code
    for i in range(0,X.shape[0]):
        pred = prediction(X[i],W,b)
        actual = y[i]
        delta = actual - pred
        if delta == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif delta == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines
data = np.loadtxt('/home/ss-root/Desktop/learning/udacity/ml-tensorflow/perceptron_data.csv', delimiter = ',')
X = data[:,:-1]
y = data[:,-1]
trainPerceptronAlgorithm(X,y,learn_rate = 0.01, num_epochs = 25)


[(array([-0.05239463]), array([-2.04919443])),
 (array([1.23772563]), array([-2.90815949])),
 (array([-39.47663703]), array([23.57864461])),
 (array([-13.13237331]), array([7.06473087])),
 (array([-9.11612538]), array([4.57527519])),
 (array([-7.79056954]), array([3.96940892])),
 (array([-6.7750263]), array([3.50523881])),
 (array([-5.97212608]), array([3.13826056])),
 (array([-5.32141098]), array([2.84084093])),
 (array([-4.78335796]), array([2.59491529])),
 (array([-4.33103935]), array([2.38817591])),
 (array([-4.09146109]), array([2.3928177])),
 (array([-3.80251597]), array([2.25914697])),
 (array([-3.54414571]), array([2.13962066])),
 (array([-3.31174122]), array([2.03210655])),
 (array([-3.10157551]), array([1.93488045])),
 (array([-2.91060228]), array([1.84653311])),
 (array([-2.73630733]), array([1.76590142])),
 (array([-2.57659722]), array([1.69201691])),
 (array([-2.4297148]), array([1.6240667])),
 (array([-2.29417429]), array([1.56136344])),
 (array([-2.16871083]), array([1.5